apiVersion: apps/v1
kind: Deployment
metadata:
  name: www
spec:
  replicas: 3
  selector:
    matchLabels:
      app: www
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: www
    spec:
      containers:
        - name: www
          image: nginx:1.18
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 200m
