apiVersion: v1
kind: LimitRange
metadata:
  name: memory-limit-range
spec:
  limits:
    - default:
        memory: 128M
      defaultRequest:
        memory: 64M
      max:
        memory: 256M
      type: Container
