apiVersion: v1
kind: Pod
metadata:
  name: proxy
  labels:
    app: proxy
spec:
  containers:
    - name: proxy
      image: nginx:1.20-alpine
      volumeMounts:
        - name: config
          mountPath: "/etc/nginx/"
  volumes:
    - name: config
      configMap:
        name: proxy-config
---
apiVersion: v1
kind: Service
metadata:
  name: proxy
  labels:
    app: proxy
spec:
  selector:
    app: proxy
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 31600
